[pytest]
filterwarnings =
    error
    ignore::starlette.exceptions.StarletteDeprecationWarning
    ignore::DeprecationWarning
addopts = -ra
strict_markers = true
markers =
    slow: slow integration tests requiring a live database
